### ISSUE TITLE
NPE when using command before initialization

### ISSUE THREAD

**Issue by SuperThunder** [SuperThunder/coen448-project#7]
### Issue
- [x] No commands should result in a crash, even if the board has not been initialized yet. There should be an error message instead.
- [x] Create a test (in ControllerTest) that runs every command except initialize and ensures no exception occurs
- [x] Add the new test case to the spreadsheet

### Output
```
COEN448 Project
Please enter a command:

p
Feb. 01, 2022 7:28:08 P.M. com.coen448.UserInputProcessor <init>
INFO: UserInputProcessor constructor got input: p
Feb. 01, 2022 7:28:08 P.M. com.coen448.UserInputProcessor processLine
INFO: Got tokens: p
Feb. 01, 2022 7:28:08 P.M. com.coen448.Main main
INFO: main got user command: PrintGrid
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.coen448.grid.Robot.printFloor()" because "this.robot" is null
	at com.coen448.grid.Controller.printGrid(Controller.java:24)
	at com.coen448.Main.main(Main.java:63)

Process finished with exit code 1
```

**Comment by Suyash-Sinha** [comment]
Created a ControllerNPETest.java class to check for null pointer exception before the board is initialized.  Added a default constructor in Controller.java to avoid  robot not being initialized and  giving a null pointer exception
